FROM node:20-alpine AS builder

WORKDIR /home/app

COPY . .

RUN yarn install && yarn build

FROM nginx:stable-alpine

COPY --from=builder /home/app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN touch /run/nginx.pid \
 && mkdir -p /var/cache/nginx \
 && chown -R nginx:nginx /run/nginx.pid /var/cache/nginx /usr/share/nginx/html /etc/nginx

USER nginx

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
