name: perfect-tv-dev
services:
  perfect-tv-api:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./api/.env
    volumes:
      - ./api/app:/home/app/app
      - ./api/swagger.json:/home/app/swagger.json
    ports:
      - 5000:5000
    depends_on:
      perfect-tv-db:
        condition: service_healthy
    init: true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - perfect-tv-net

  perfect-tv-graphql:
    build:
      context: ./graphql
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./graphql/.env
    volumes:
      - ./graphql/app:/home/app/app
    ports:
      - 5001:5001
    depends_on:
      perfect-tv-db:
        condition: service_healthy
      perfect-tv-api:
        condition: service_started
    networks:
      - perfect-tv-net

  perfect-tv-client:
    build:
      context: ./client
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./client/.env
    volumes:
      - ./client:/home/app
      - /home/app/node_modules
    ports:
      - 5173:5173
    depends_on:
      perfect-tv-db:
        condition: service_healthy
      perfect-tv-api:
        condition: service_started
      perfect-tv-graphql:
        condition: service_started
    networks:
      - perfect-tv-net

  perfect-tv-db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: perfecttvdb
    volumes:
      - ./perfect-tv-dev-db-data:/var/lib/postgresql/data
    networks:
      - perfect-tv-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "perfecttvdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

networks:
  perfect-tv-net:

volumes:
  perfect-tv-dev-db-data: