FROM node:20.5.0-alpine3.18 AS builder

WORKDIR /home/app

COPY ./package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Final image

FROM node:20.5.0-alpine3.18

WORKDIR /home/app

COPY --from=builder /home/app/dist ./app
COPY --from=builder /home/app/package*.json ./
COPY --from=builder /home/app/tsconfig.json ./tsconfig.json

RUN npm install --omit=dev

EXPOSE 5001

CMD ["node", "app/entrypoint.js"]